name: LaggyKick
version: 1.0.0
author: applqpak
api:
- 1.0.0
- 2.0.0
main: LaggyKick\Main
commands:
  ping:
    description: "Ping A Player."
    usage: "/ping <player>"
    permission: laggykick.command.ping
permissions:
  laggykick.command.ping:
    default: op
